### ISSUE TITLE
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32') in closest_location()

### ISSUE THREAD

**Issue by sungeunbae** [ucgmsim/seisfinder2#61]
baes@mahuika02: /nesi/nobackup/nesi00213/RunFolder/Cybershake/v18p6_2$ python /nesi/project/nesi00213/deploy/seisfinder2/site/site_search_deagg.py SA_5p0 -s -41.7314 171.8001 -e 0.0021

**Comment by viktor76525** [comment]
can't test from hypocentre because config.yaml has absolute paths for some reason
can't test from mahuika because permission issues
